[[execbundle]]
arch = "x86_64"
os = "linux"
git-tree-sha1 = "9855c7292594fe8c8389b5027b010925c5eca2bc"

    [[execbundle.download]]
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/linux-x86_64.tar.gz"
    sha256 = "5f94b7530ca246cf2997153e28d15468f23c9262aaef6b4afa84a1f6be1e41d3"
[[execbundle]]
arch = "aarch64"
os = "linux"
git-tree-sha1 = "c893abea14300ddd19875d49a2503675568e509b"

    [[execbundle.download]]
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/linux-aarch64.tar.gz"
    sha256 = "a18ce59d84798d6806288cb5933df5d812012f4db652b0198cfa46583f9eec3a"
[[execbundle]]
arch = "x86_64"
os = "macos"
git-tree-sha1 = "0caa21a6cce6cefad50d5c2f2ceb9ab41a7825ca"

    [[execbundle.download]]
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/macos-x86_64.tar.gz"
    sha256 = "1b842e57828234342694d5a05b37ad332ddd2377b383e6b2ad5af274a9b29e54"
[[execbundle]]
arch = "aarch64"
os = "macos"
git-tree-sha1 = "31992b68e18841a9594a9c4aa9689227d521f2fa"

    [[execbundle.download]]
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/macos-aarch64.tar.gz"
    sha256 = "afc3fa8eba547f7e3288ae576afb397a95b691cbaaa896f5a8125ef9f9911818"
[[execbundle]]
arch = "x86_64"
os = "freebsd"
git-tree-sha1 = "53508e250df04f91c4228da9e609a2a6776fdd77"

    [[execbundle.download]]
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/freebsd-x86_64.tar.gz"
    sha256 = "86097281c5b1bf10b02eda3c7ebc7d864576655e9f4accdfe53997c2ae9c16dc"
[[execbundle]]
arch = "aarch64"
os = "freebsd"
git-tree-sha1 = "581d3a8d8434966ca691e1259c326d0dbc5e1b9e"

    [[execbundle.download]]
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/freebsd-aarch64.tar.gz"
    sha256 = "b271d765edb45f0bd5d45c777d30d0f6090afb97acdd20efdc986e88bd7ce6cd"
[[execbundle]]
arch = "arm"
os = "freebsd"
git-tree-sha1 = "ba57fb363b2045a09c70bb35296a71abd6e65fa8"

    [[execbundle.download]]
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/freebsd-arm.tar.gz"
    sha256 = "ce078816e1a242457eecca20ca7a60678b5469fa2549fb762fefd7ab9307ff88"
[[execbundle]]
arch = "x86_64"
os = "openbsd"
git-tree-sha1 = "15b7bf5dc4a05448e8292469929c6adacba0e124"

    [[execbundle.download]]
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/openbsd-x86_64.tar.gz"
    sha256 = "f01cb0d023fe05f6918d604f88e39b4841fa0848eeb2ba209e351f584b3f5cb6"
[[execbundle]]
arch = "aarch64"
os = "openbsd"
git-tree-sha1 = "fe766ae95a5f9616bce761d857afbe207f6d8905"

    [[execbundle.download]]
    url = "https://github.com/tecosaur/DaemonicCabal.jl/releases/download/0.5.0/openbsd-aarch64.tar.gz"
    sha256 = "891ac2f383887dd0e27fe249a1980a584f7c94bdccab6fe5332d4703e82a943b"
